Nunit test

diff --git a/.github/workflows/nunit.yml b/.github/workflows/nunit.yml
--- a/.github/workflows/nunit.yml
+++ b/.github/workflows/nunit.yml
@@ -37,10 +37,35 @@ jobs:
           
           # Extract to project root directory
           unzip -o iris_mac_unity.zip -d $GITHUB_WORKSPACE
-          ls $GITHUB_WORKSPACE
           
           # Clean up temporary directory
           cd $GITHUB_WORKSPACE
           rm -rf temp_download
           
           echo "Successfully downloaded and extracted Iris Mac Unity package to project root directory"
+      
+      - name: Run NUnit tests
+        run: |
+          ls $GITHUB_WORKSPACE
+          # Find directory starting with iris and store in variable
+          IRIS_DIR=$(find $GITHUB_WORKSPACE -type d -name "iris*" | head -n 1)
+          
+          if [ -z "$IRIS_DIR" ]; then
+            echo "Error: No directory starting with iris found"
+            exit 1
+          else
+            echo "Found Iris directory: $IRIS_DIR"
+          fi
+
+          # Check if IRIS_DIR name contains DCG
+          if [[ "$IRIS_DIR" == *"DCG"* ]]; then
+            echo "IRIS Type is DCG"
+            AGORA_LIB_NAME=$GITHUB_WORKSPACE/$IRIS_DIR/Debugger/MAC/IrisDebugger.framework/Versions/A/IrisDebugger
+            DEBUG_LIB_NAME=$GITHUB_WORKSPACE/$IRIS_DIR/Debugger/MAC/IrisDebugger.framework/Versions/A/IrisDebugger
+            sh terra/nunit_run.sh $AGORA_LIB_NAME $DEBUG_LIB_NAME ${{ inputs.fully_qualified_name }}
+          else
+            echo "IRIS Type is RTM"
+          fi
+
+          echo "NUnit tests completed"
+
