check csharp codes compile

diff --git a/.github/workflows/terra.yml b/.github/workflows/terra.yml
--- a/.github/workflows/terra.yml
+++ b/.github/workflows/terra.yml
@@ -45,3 +45,15 @@ jobs:
           pull-request-title: |
             [AUTO] Generate codes by terra(${{ inputs.rtc_version }})
           add-paths: .
+
+      - name: Check csharp codes compile
+        run: |
+          cd Agora-C_Sharp_RTC-SDK_UT
+          dotnet restore Agora_C_Sharp_SDK_UT.sln
+          dotnet build Agora_C_Sharp_SDK_UT.sln --configuration Release
+          if [ $? -ne 0 ]; then
+            echo "csharp codes compile error"
+            exit 1
+          else
+            echo "csharp codes compile success"
+          fi
