GitHub action/main (#500)
* fix replace_rtc_version.sh error

* github action

* github actions

* fix error

* github action

* fix sh error

* fix yarn

* remove porxy

* exclude

* titile

* check csharp codes compile

---------

Co-authored-by: 夏羊群 <xiayangqun@agora.io>

diff --git a/.github/workflows/terra.yml b/.github/workflows/terra.yml
--- a/.github/workflows/terra.yml
+++ b/.github/workflows/terra.yml
@@ -1,4 +1,4 @@
-name: Generate codes
+name: Generate codes and create pull request
 
 on:
   workflow_dispatch:
@@ -18,22 +18,22 @@ jobs:
           fetch-depth: 0
           token: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Setup
+        uses: ./.github/setup
+
       - name: Replace rtc version
         run: sh terra/replace_rtc_version.sh ${{ inputs.rtc_version }}
 
-      # - name: Generate code and comment by terra
-      #   uses: AgoraIO-Extensions/actions/.github/actions/generate@main
-      #   with:
-      #     working-directory: "terra"
-      #     github-token: ${{ secrets.GH_TOKEN }}
-      #     generate-code: true
-      #     generate-comment: true
-      #     generate-code-command: |
-      #       sh generate-prepare.sh
-      #       sh generate-code.sh
-      #     generate-comment-command: |
-      #       sh generate-comment.sh
-
+      - name: Generate code and comment by terra
+        uses: AgoraIO-Extensions/actions/.github/actions/generate@main
+        with:
+          working-directory: "terra"
+          github-token: ${{ secrets.GH_TOKEN }}
+          generate-code: true
+          generate-comment: false
+          generate-code-command: |
+            sh prepare.sh
+            sh rtc.sh
 
       - name: Create pull request
         uses: AgoraIO-Extensions/actions/.github/actions/pr@main
@@ -45,3 +45,15 @@ jobs:
           pull-request-title: |
             [AUTO] Generate codes by terra(${{ inputs.rtc_version }})
           add-paths: .
+
+      - name: Check csharp codes compile
+        run: |
+          cd Agora-C_Sharp_RTC-SDK_UT
+          dotnet restore Agora_C_Sharp_SDK_UT.sln
+          dotnet build Agora_C_Sharp_SDK_UT.sln --configuration Release
+          if [ $? -ne 0 ]; then
+            echo "csharp codes compile error"
+            exit 1
+          else
+            echo "csharp codes compile success"
+          fi
